### ISSUE TITLE
PEP-8 standards

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#194]
When the python code is somoehow final (not yet), we should have a look at enforce python style standards.

**Comment by sco1** [comment]
Hi Ander, is this something you're open for collaboration on?

**Comment by AnderBiguri** [comment]
Hi @sco1 ! 
Apologies, I do not know who you are (changed nickname since?).

But yes! absolutely, everything is open to collaboration :)

**Comment by sco1** [comment]
I'm happy to work on the PR to add what's decided on. I'll put out some things to consider first, as there are some stylistic choices to make for a few in order to set up the desired linting errors to enforce.

#### Automatic Code Formatting with [black](https://github.com/psf/black)
This is an autoformatter to (mostly) PEP8 standards with one configuration option: line length. It may clash with some individual styles but it has the advantage of being consistent; basically run it and don't worry about differences in code style.

#### Code Linting with [flake8](https://flake8.pycqa.org/en/latest/)
In addition to the built-in errors, I'd like to suggest some additional plugins:

  * [flake8-docstrings](https://gitlab.com/pycqa/flake8-docstrings)
  * [flake8-import-order](https://github.com/PyCQA/flake8-import-order)
  * [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear)
  * [pep8-naming](https://github.com/PyCQA/pep8-naming)

Of these, flake8-docstrings and pep8-naming probably have the biggest impact on style based on the selection of errors to enforce.

I'll also throw out [flake8-annotations](https://github.com/sco1/flake8-annotations) (caveat, I wrote this) if you're interested in adding type annotations to the codebase. Like [mypy](https://github.com/python/mypy), it also supports gradual addition of typing.

Here's the template I start with:

```
[flake8]
max-line-length=100
docstring-convention=all
import-order-style=pycharm
ignore=
    P102,B311,W503,E226,S311,
    # Missing Docstrings
    D100,D104,D105,D107,
    # Docstring Whitespace
    D203,D212,D214,D215,
    # Docstring Quotes
    D301,D302,
    # Docstring Content
    D400,D401,D402,D404,D405,D406,D407,D408,D409,D410,D411,D412,D413,D414,D416,D417,
    # Type Annotations
    ANN002,ANN003,ANN101,ANN102,ANN204,ANN206,
    # pep8-naming
    N802,N806,N815,
exclude=
    __pycache__,.cache,
    venv,.venv,
```

Happy to break down these error codes if you don't want to dig through the documentation.

#### Pre-commit enforcement with [pre-commit](https://pre-commit.com/)
This framework can optionally be used to install pre-commit hooks to run various checks and refuse commits with issues. A configuration file is included with the repository & this can be installed by the developer.

Here's the template I start with:

```yaml
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.1
    hooks:
    -   id: python-check-blanket-noqa
```
